FROM maven:3.8.4-openjdk-11-slim AS build
RUN apt-get update && apt-get install -y git nodejs npm && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY . /app/
RUN npm install && \
    mvn package
EXPOSE 8081
CMD [ "mvn", "spring-boot:run", "-Dspring-boot.run.arguments=--server.port=8081"]
