version: '3.8'
services:
  app:
    # build: .
    image: uwbfritz/aicybersec:latest
    container_name: aicybersec
    ports:
      - "8080"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - app
    networks:
      - app-network

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    restart: always

networks:
  app-network:
    driver: bridge

