version: '3.8'
services:
  fargo:
    # build: .
    image: uwbfritz/aicybersec:latest
    container_name: aicybersec
    ports:
      - "8080"
    networks:
      - uwtai-network
  tacoma:
    # build: .
    image: uwbfritz/uwtaccybersec:latest
    container_name: uwtaccybersec
    ports:
      - "8081"
    networks:
      - uwtai-network
  nginx:
    image: nginx:alpine
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - fargo
    networks:
      - uwtai-network
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    restart: always
networks:
  uwtai-network:
#     driver: bridge

